import Image from "next/image";
import { ArrowDown, ArrowRight, ArrowUpRight, Building2, Check, Factory, GraduationCap, HardHat, Landmark, Mail, MapPin, MessageCircle, Phone, ShieldCheck, Sparkles, Truck, Users2, Waves } from "lucide-react";
import { Navigation } from "@/components/navigation";
import { Reveal } from "@/components/reveal";
import { Counter } from "@/components/counter";
import { Projects } from "@/components/projects";
import { FAQ } from "@/components/faq";
import { ContactForm } from "@/components/contact-form";

const divisionData = [
  { id: "tent-king", no: "01", name: "Tent King", line: "Infrastructure & Manufacturing", description: "The foundation of the group. In-house manufacturing, supply and rental of temporary structures and event infrastructure.", logo: "/logos/tent-king.webp", light: true, services: ["Tent manufacturing", "Stretch & marquee tents", "Temporary warehousing", "Custom branded structures", "Flooring & furniture"] },
  { id: "loo-king", no: "02", name: "Loo-King", line: "Sanitation Solutions", description: "Hygienic, compliant sanitation infrastructure backed by a dedicated fleet and professional service teams.", logo: "/logos/loo-king.webp", services: ["Portable & VIP toilets", "Construction toilets", "Septic tank pumping", "Drain cleaning & jetting", "Wastewater management"] },
  { id: "eventing-king", no: "03", name: "Eventing King", line: "Events & Experiences", description: "Integrated planning, production, styling and event management—delivered from concept through execution.", logo: "/logos/eventing-king.webp", services: ["Corporate events", "Furniture & equipment", "Décor & styling", "Lighting & staging", "Event management"] },
  { id: "prop-king", no: "04", name: "Prop King", line: "Property & Facilities", description: "Practical property and facilities solutions built around performance, care and long-term asset value.", logo: "/logos/prop-king.webp", services: ["Property management", "Facilities & maintenance", "Cleaning", "Asset management", "Development"] },
];

const industries = [
  [Landmark, "Government", "Dependable delivery for public-sector programmes and facilities."], [HardHat, "Construction", "Rapid-deploy infrastructure and site sanitation."], [Factory, "Mining & industrial", "Robust solutions for demanding operational environments."], [GraduationCap, "Education", "Temporary spaces and facilities for institutions."], [Building2, "Corporate", "Brand-ready environments, workplaces and events."], [Sparkles, "Events", "Complete infrastructure and experience production."], [Waves, "Municipalities", "Scalable public sanitation and infrastructure support."], [Users2, "Private sector", "Flexible capability for projects of every scale."],
];

export default function Home() {
  return <>
    <Navigation />
    <main id="main">
      <section id="top" className="relative min-h-[780px] overflow-hidden bg-black pt-[76px] text-white lg:min-h-screen">
        <Image src="https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=2200&q=90" alt="Large-scale infrastructure project at dusk" fill priority sizes="100vw" className="object-cover object-center" />
        <div className="hero-scrim absolute inset-0"/><div className="grid-lines absolute inset-0 opacity-40"/>
        <div className="container-site relative z-10 flex min-h-[704px] items-center py-20 lg:min-h-[calc(100vh-76px)]">
          <div className="max-w-[960px]">
            <Reveal><p className="eyebrow text-white">Integrated solutions. National capability.</p></Reveal>
            <Reveal delay={.08}><h1 className="font-display mt-8 text-balance text-[clamp(3.5rem,8.4vw,8rem)] font-black uppercase leading-[.84] tracking-[-.07em]">Building Spaces.<br/><span className="text-white/52">Enabling Experiences.</span><br/>Delivering <span className="text-king-red">Solutions.</span></h1></Reveal>
            <Reveal delay={.16} className="mt-10 flex flex-col gap-6 sm:flex-row sm:items-center">
              <a href="#contact" className="focus-ring inline-flex items-center justify-center gap-3 bg-king-red px-7 py-4 text-sm font-black uppercase tracking-wider text-white transition hover:bg-white hover:text-black">Request a quote <ArrowRight size={17}/></a>
              <a href="#divisions" className="focus-ring inline-flex items-center justify-center gap-3 border border-white/40 px-7 py-4 text-sm font-black uppercase tracking-wider transition hover:bg-white hover:text-black">View our divisions <ArrowDown size={17}/></a>
            </Reveal>
          </div>
        </div>
        <div className="absolute bottom-0 right-0 z-20 hidden border-l border-t border-white/20 bg-black/65 backdrop-blur-md lg:grid lg:grid-cols-3">
          {[["2010", "Established"], ["04", "Specialist divisions"], ["ZA", "National service"]].map(([v,l])=><div key={l} className="min-w-48 border-r border-white/15 px-7 py-6"><p className="text-2xl font-black">{v}</p><p className="mt-1 text-[10px] font-bold uppercase tracking-[.18em] text-white/55">{l}</p></div>)}
        </div>
      </section>

      <section id="about" className="section-pad overflow-hidden">
        <div className="container-site grid gap-14 lg:grid-cols-[.75fr_1.25fr] lg:gap-24">
          <Reveal><p className="eyebrow">Tent King Group</p><p className="mt-8 max-w-sm text-lg leading-8 text-neutral-600">Since 2010, we have helped organisations, communities, businesses and government institutions create the infrastructure they need to operate, celebrate, grow and succeed.</p></Reveal>
          <Reveal delay={.08}><h2 className="font-display text-balance text-[clamp(3rem,6vw,6.5rem)] font-black uppercase leading-[.9]">Built on quality.<br/><span className="text-neutral-300">Driven by service.</span></h2><div className="mt-12 grid gap-8 border-t pt-8 sm:grid-cols-2"><p className="leading-7 text-neutral-600">What began as a specialist tent manufacturing and rental business has evolved into a diversified solutions group serving clients across South Africa.</p><p className="leading-7 text-neutral-600">Today, four specialist divisions combine manufacturing capability, a dedicated sanitation fleet and experienced project teams under one accountable partner.</p></div></Reveal>
        </div>
      </section>

      <section className="border-y border-neutral-200 bg-king-grey">
        <div className="container-site grid gap-px bg-neutral-200 lg:grid-cols-3">
          {[
            ["Mission", "Make complex projects simpler", "To provide reliable, integrated infrastructure solutions supported by exceptional service, practical expertise and accountable delivery."],
            ["Vision", "Enable progress at every scale", "To be South Africa’s trusted partner for the spaces, systems and services that help organisations and communities move forward."],
            ["Values", "Quality. Reliability. Service.", "We build with care, respond with urgency, communicate clearly and take ownership of the outcome—from first brief to final handover."],
          ].map(([label,title,copy],i)=><Reveal key={label} delay={i*.05}><article className="min-h-80 bg-king-grey p-8 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-king-red">{label}</p><h3 className="mt-12 text-2xl font-black">{title}</h3><p className="mt-5 leading-7 text-neutral-600">{copy}</p></article></Reveal>)}
        </div>
      </section>

      <section className="bg-king-ink text-white">
        <div className="container-site grid lg:grid-cols-2">
          <div className="section-pad lg:pr-20"><Reveal><p className="eyebrow">Our evolution</p><h2 className="font-display mt-7 text-5xl font-black uppercase leading-[.92] sm:text-7xl">One vision.<br/>Built to scale.</h2></Reveal>
            <div className="mt-14 border-l border-white/20">
              {[["2010", "Tent King established", "A specialist manufacturer and rental partner founded around reliability and exceptional service."], ["Growth", "Manufacturing at the core", "On-site production expands quality control, customisation and turnaround capability."], ["Diversification", "Specialist divisions emerge", "Sanitation, eventing and property capabilities create a truly integrated offer."], ["Today", "National project partner", "Four divisions support public and private-sector clients across South Africa."]].map(([year,title,desc],i)=><Reveal key={title} delay={i*.05} className="relative grid gap-2 border-b border-white/15 py-7 pl-8 sm:grid-cols-[120px_1fr]"><span className="absolute -left-[5px] top-8 h-[9px] w-[9px] bg-king-red"/><p className="text-xs font-black uppercase tracking-[.18em] text-king-red">{year}</p><div><h3 className="text-xl font-black">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-white/55">{desc}</p></div></Reveal>)}
            </div>
          </div>
          <div className="relative min-h-[580px] lg:min-h-full"><Image src="https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=1400&q=85" alt="Construction and engineering team on site" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover grayscale"/><div className="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-8 sm:p-12"><p className="max-w-md text-2xl font-black leading-tight sm:text-3xl">Practical solutions backed by experience, reliability and a commitment to quality.</p></div></div>
        </div>
      </section>

      <section id="divisions" className="section-pad bg-king-grey">
        <div className="container-site"><Reveal className="grid gap-8 lg:grid-cols-2 lg:items-end"><div><p className="eyebrow">Our divisions</p><h2 className="font-display mt-7 text-5xl font-black uppercase leading-[.9] sm:text-7xl">Four specialists.<br/>One standard.</h2></div><p className="max-w-lg text-lg leading-8 text-neutral-600 lg:justify-self-end">A connected group model means fewer handovers, clearer accountability and the right expertise at every stage.</p></Reveal>
          <div className="mt-16 grid gap-px bg-neutral-300 lg:grid-cols-2">{divisionData.map((d,i)=><Reveal key={d.name} delay={i*.05}><article id={d.id} className="group min-h-[620px] bg-white p-6 transition hover:bg-black hover:text-white sm:p-10"><div className="flex items-start justify-between"><span className="text-xs font-black text-king-red">{d.no}</span><ArrowUpRight className="text-neutral-300 transition group-hover:text-king-red"/></div><div className={`relative mt-12 h-28 w-full max-w-sm overflow-hidden ${d.light ? "bg-white" : "bg-black"}`}><Image src={d.logo} alt={`${d.name} logo`} fill sizes="400px" className="object-contain object-left"/></div><div className="mt-10 border-t border-neutral-200 pt-8 group-hover:border-white/20"><p className="text-xs font-black uppercase tracking-[.18em] text-king-red">{d.line}</p><p className="mt-4 max-w-xl leading-7 text-neutral-600 transition group-hover:text-white/60">{d.description}</p><ul className="mt-8 grid gap-3 sm:grid-cols-2">{d.services.map(s=><li key={s} className="flex items-center gap-2 text-sm font-bold"><Check size={15} className="text-king-red"/>{s}</li>)}</ul></div></article></Reveal>)}</div>
        </div>
      </section>

      <section className="bg-king-red py-8 text-white"><div className="container-site flex flex-wrap items-center justify-between gap-6"><p className="text-xs font-black uppercase tracking-[.2em]">Integrated capability</p><p className="font-display text-2xl font-black uppercase sm:text-4xl">Manufacture. Deploy. Operate. Maintain.</p><ShieldCheck size={32}/></div></section>

      <section id="projects" className="section-pad"><div className="container-site"><Reveal className="mb-14 grid gap-8 lg:grid-cols-2 lg:items-end"><div><p className="eyebrow">Selected capabilities</p><h2 className="font-display mt-7 text-5xl font-black uppercase leading-[.9] sm:text-7xl">Built for the<br/>real world.</h2></div><p className="max-w-lg text-sm leading-7 text-neutral-500 lg:justify-self-end">Representative project imagery shown while the final Tent King Group portfolio is curated.</p></Reveal><Projects/></div></section>

      <section id="industries" className="section-pad bg-black text-white"><div className="container-site"><Reveal><p className="eyebrow">Industries served</p><h2 className="font-display mt-7 max-w-5xl text-balance text-5xl font-black uppercase leading-[.9] sm:text-7xl">Capability that moves across sectors.</h2></Reveal><div className="mt-16 grid border-l border-t border-white/15 sm:grid-cols-2 lg:grid-cols-4">{industries.map(([Icon,name,desc],i)=>{const I=Icon as typeof Building2; return <Reveal key={name as string} delay={i*.035}><article className="min-h-64 border-b border-r border-white/15 p-7 transition hover:bg-white hover:text-black"><I className="text-king-red" size={28}/><h3 className="mt-12 text-xl font-black">{name as string}</h3><p className="mt-3 text-sm leading-6 opacity-55">{desc as string}</p></article></Reveal>})}</div></div></section>

      <section className="section-pad bg-king-grey"><div className="container-site"><Reveal className="grid gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="eyebrow">Why Tent King Group</p><h2 className="font-display mt-7 text-5xl font-black uppercase leading-[.9] sm:text-7xl">Confidence,<br/>built in.</h2></div><p className="max-w-lg self-end text-lg leading-8 text-neutral-600">From procurement to deployment, every capability is shaped around practical delivery, clear ownership and professional service.</p></Reveal><div className="mt-16 grid gap-px bg-neutral-300 sm:grid-cols-2 lg:grid-cols-3">{[["15+", "Years established", "Operating since 2010"],["04", "Specialist divisions", "Connected group capability"],["01", "Trusted partner", "Clear accountability"],["ZA", "Nationwide service", "Projects across South Africa"],["24/7", "Operational mindset", "Built for urgent requirements"],["100%", "In-house focus", "Manufacturing control"]].map(([v,l,d],i)=><Reveal key={l} delay={i*.04}><div className="min-h-56 bg-white p-8"><p className="font-display text-6xl font-black tracking-tighter text-king-red">{i===0?<><Counter value={15} suffix="+"/></>:v}</p><p className="mt-8 font-black">{l}</p><p className="mt-2 text-sm text-neutral-500">{d}</p></div></Reveal>)}</div></div></section>

      <section className="section-pad"><div className="container-site grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:gap-24"><Reveal><p className="eyebrow">How we work</p><h2 className="font-display mt-7 text-5xl font-black uppercase leading-[.9] sm:text-6xl">Complex need.<br/>Clear response.</h2><p className="mt-7 max-w-md leading-7 text-neutral-600">A disciplined delivery model keeps scope, safety, logistics and accountability aligned from first brief to final handover.</p></Reveal><div>{[["01","Understand", "We define the operational need, site, timeline and success criteria."],["02","Engineer", "The right division specialists shape a practical, fit-for-purpose solution."],["03","Mobilise", "Manufacturing, fleet and project teams prepare for coordinated deployment."],["04","Deliver", "On-site execution and ongoing support keep the project moving."]].map(([n,t,d],i)=><Reveal key={t} delay={i*.05} className="grid gap-4 border-t py-7 sm:grid-cols-[70px_160px_1fr]"><span className="text-xs font-black text-king-red">{n}</span><h3 className="text-xl font-black">{t}</h3><p className="leading-7 text-neutral-600">{d}</p></Reveal>)}</div></div></section>

      <section className="section-pad bg-king-grey"><div className="container-site grid gap-14 lg:grid-cols-2 lg:gap-24"><Reveal><p className="eyebrow">Frequently asked</p><h2 className="font-display mt-7 text-5xl font-black uppercase leading-[.9] sm:text-7xl">The practical<br/>details.</h2></Reveal><Reveal delay={.08}><FAQ/></Reveal></div></section>

      <section className="relative overflow-hidden bg-king-red py-20 text-white"><div className="grid-lines absolute inset-0"/><div className="container-site relative flex flex-col items-start justify-between gap-10 lg:flex-row lg:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em]">Start a conversation</p><h2 className="font-display mt-5 max-w-5xl text-5xl font-black uppercase leading-[.9] sm:text-7xl">One brief.<br/>A group of solutions.</h2></div><a href="#contact" className="focus-ring inline-flex shrink-0 items-center gap-3 bg-black px-7 py-4 text-sm font-black uppercase tracking-wider transition hover:bg-white hover:text-black">Discuss your project <ArrowRight size={17}/></a></div></section>

      <section id="contact" className="section-pad"><div className="container-site grid gap-16 lg:grid-cols-[.85fr_1.15fr] lg:gap-24"><Reveal><p className="eyebrow">Contact</p><h2 className="font-display mt-7 text-5xl font-black uppercase leading-[.9] sm:text-7xl">Let’s build<br/>what’s next.</h2><p className="mt-7 max-w-md text-lg leading-8 text-neutral-600">Tell us what needs to happen. Our team will connect the right capability and help define the next step.</p><div className="mt-12 grid gap-5"><a href="tel:+27119720053" className="group flex items-center gap-5 border-t pt-5"><Phone className="text-king-red"/><div><p className="text-xs font-bold uppercase tracking-wider text-neutral-500">Johannesburg office</p><p className="mt-1 text-lg font-black group-hover:text-king-red">011 972 0053</p></div></a><a href="mailto:info@tentsking.co.za" className="group flex items-center gap-5 border-t pt-5"><Mail className="text-king-red"/><div><p className="text-xs font-bold uppercase tracking-wider text-neutral-500">Email</p><p className="mt-1 text-lg font-black group-hover:text-king-red">info@tentsking.co.za</p></div></a><div className="flex items-center gap-5 border-t pt-5"><MapPin className="text-king-red"/><div><p className="text-xs font-bold uppercase tracking-wider text-neutral-500">Head office</p><p className="mt-1 max-w-sm font-black">41 Mooifontein Road, Norkem Park, Kempton Park, 1618</p></div></div></div></Reveal><Reveal delay={.08}><ContactForm/></Reveal></div></section>

      <section className="h-[420px] grayscale"><iframe title="Tent King Group location map" src="https://www.google.com/maps?q=41%20Mooifontein%20Road%2C%20Norkem%20Park%2C%20Kempton%20Park&output=embed" width="100%" height="100%" loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="border-0"/></section>
    </main>

    <footer className="bg-black text-white"><div className="container-site py-16"><div className="grid gap-12 border-b border-white/15 pb-14 lg:grid-cols-[1.3fr_.7fr_.7fr]"><div><p className="font-display text-3xl font-black uppercase">Tent King Group</p><p className="mt-5 max-w-md leading-7 text-white/50">Building spaces. Enabling experiences. Delivering solutions across South Africa since 2010.</p></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-king-red">Navigate</p><div className="mt-5 grid gap-3 text-sm font-bold"><a href="#about">About</a><a href="#divisions">Divisions</a><a href="#projects">Projects</a><a href="#industries">Industries</a><a href="#contact">Contact</a></div></div><div><p className="text-xs font-black uppercase tracking-[.18em] text-king-red">Connect</p><div className="mt-5 grid gap-3 text-sm font-bold"><a href="tel:+27119720053">011 972 0053</a><a href="tel:+27665794055">066 579 4055</a><a href="mailto:info@tentsking.co.za">info@tentsking.co.za</a></div></div></div><div className="grid grid-cols-2 gap-3 border-b border-white/15 py-10 lg:grid-cols-4">{divisionData.map(d=><div key={d.name} className={`relative h-20 overflow-hidden ${d.light?"bg-white":"bg-black"}`}><Image src={d.logo} alt={`${d.name} division logo`} fill sizes="300px" className="object-contain p-2"/></div>)}</div><div className="flex flex-col gap-3 pt-8 text-xs text-white/45 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Tent King Group. All rights reserved.</p><div className="flex gap-5"><a href="#">Privacy</a><a href="#">Terms</a><a href="#top">Back to top ↑</a></div></div></div></footer>

    <a href="#contact" aria-label="Request a quote" className="focus-ring fixed bottom-5 left-5 z-40 hidden items-center gap-3 bg-king-red px-5 py-4 text-xs font-black uppercase tracking-wider text-white shadow-2xl transition hover:bg-black sm:flex"><ArrowUpRight size={17}/> Quote</a>
    <a href="https://wa.me/27665794055?text=Hello%20Tent%20King%20Group%2C%20I%27d%20like%20to%20discuss%20a%20project." aria-label="Contact Tent King Group on WhatsApp" className="focus-ring fixed bottom-5 right-5 z-40 flex h-14 w-14 items-center justify-center bg-black text-white shadow-2xl transition hover:bg-king-red"><MessageCircle/></a>
  </>;
}
